def dyld_framework(dirname: str, framework: str, version: str = None) -> str: ...

_C_ARY_B: bytes
_C_ARY_E: bytes
_C_BOOL: bytes
_C_BYCOPY: bytes
_C_BYREF: bytes
_C_CHR: bytes
_C_CLASS: bytes
_C_DBL: bytes
_C_FLT: bytes
_C_ID: bytes
_C_IN: bytes
_C_INOUT: bytes
_C_INT: bytes
_C_LNG: bytes
_C_LNGLNG: bytes
_C_LNG_LNG: bytes
_C_NSBOOL: bytes
_C_ONEWAY: bytes
_C_OUT: bytes
_C_PTR: bytes
_C_SEL: bytes
_C_SHT: bytes
_C_STRUCT_B: bytes
_C_STRUCT_E: bytes
_C_UCHR: bytes
_C_UINT: bytes
_C_ULNG: bytes
_C_ULNGLNG: bytes
_C_ULNG_LNG: bytes
_C_UNDEF: bytes
_C_UNICHAR: bytes
_C_UNION_B: bytes
_C_UNION_E: bytes
_C_USHT: bytes
_C_VOID: bytes
